AA1/app.py
from flask import Flask, render_template, request, redirect, session
import os

from flask import Flask
from flask_migrate import Migrate
from routes.blueprint import blueprint

STATIC_DIR = os.path.abspath('static')

def create_app():
    app = Flask(__name__)  
    app.config.from_object('config')  
    app = Flask(__name__, static_folder=STATIC_DIR)
    app.use_static_for_root = True
    app.secret_key = 'HI'
    return app

app = create_app()  

app.register_blueprint(blueprint, url_prefix='')

if __name__ == '__main__': 
    app.run(host='127.0.0.1', port=5000, debug=True)

AA1/controllers/controller.py
import json
from flask import render_template, request, redirect, session, jsonify, make_response
from reportlab.pdfgen import canvas
from flask_session import Session
import io, time

products = [{'id': 1,
             'name': 'Robo Dog',
             'image': 'toy1.png',
             'rating': 4, 
             'selling_price': 900,
             'marked_price': 1000,
             'status': 'For Sale'
             },{'id': 2,
             'name': 'Alza',
             'image': 'toy2.png',
             'rating': 5, 
             'selling_price': 1900,
             'marked_price': 2000,
             'status': 'For Sale'
             },{'id': 3,
             'name': 'Electric Toy Car',
             'image': 'toy3.png',
             'rating': 5, 
             'selling_price': 2900,
             'marked_price': 3000,
             'status': 'For Sale'
             },{'id': 4,
             'name': 'Lego house',
             'image': 'toy4.png',
             'rating': 4, 
             'selling_price': 500,
             'marked_price': 1000,
             'status': 'For Sale'
             },{'id': 5,
             'name': 'Toy car',
             'image': 'toy5.png',
             'rating': 4, 
             'selling_price': 900,
             'marked_price': 1000,
             'status': 'For Sale'
             },{'id': 6,
             'name': 'Plane',
             'image': 'toy6.png',
             'rating': 5, 
             'selling_price': 1900,
             'marked_price': 2000,
             'status': 'For Sale'
             },{'id': 7,
             'name': 'Crane',
             'image': 'toy7.png',
             'rating': 5, 
             'selling_price': 2900,
             'marked_price': 3000,
             'status': 'Not For Sale'
             },{'id': 8,
             'name': 'Truck',
             'image': 'toy8.png',
             'rating': 4, 
             'selling_price': 500,
             'marked_price': 1000,
             'status': 'Not For Sale'
             },
                
]

def index():
    print("incoming request")
    # Wait for 5 seconds
    time.sleep(5)
    if not session.get("user_id"):
        return redirect("/login")
        
    return render_template('dashboard/dashboard.html', products= products, user_id=session.get('user_id'))
    
def login():
    if request.method == "POST":
        session["user_id"] = request.form.get("email")
        print("Session name", request.form.get("email"))
        return redirect("/")
    return render_template("login/login.html")

def logout():
    session["user_id"] = None
    session["orders"] = None
    session["cart"] = None
    return redirect("/")

def order():
    productId = request.args.get('id')
    selectedProduct = None 
    for product in products:
        if product['id'] == int(productId):
            selectedProduct = product

    if selectedProduct['status'] == 'Not For Sale':
        return redirect('/')    
    
    return render_template("order/order.html", product=selectedProduct)

def addAddress():
   return redirect("/")

def addToCart():
    data = request.json

    ### Secure the website by taking important data such as price from server side only###
    
    # Loop through each product in products
    for product in products:
        # Check id product['id'] matches with the product_id in data
        if product['id'] == int(data['product_id']):
            # Store product in selectedProduct
            selectedProduct = product
    
    # Set price, total, name, image of the data using selectedProduct
    data['price'] = selectedProduct['selling_price']
    data['total'] = selectedProduct['selling_price'] * data['quantity']
    data['name'] = selectedProduct['name']
    data['image'] = 'static/images/' + selectedProduct['image']

    cart = session.get('cart', [])

    if( not cart):
        cart = []
        
    cart.append(data)

    session['cart'] = cart

    data = { 
            "message" : "Data Structures and Algorithms", 
        } 
    return jsonify(data) 

def cart():
    cart = session.get('cart', [])
    totalPrice = 0
    if (cart):
        totalPrice = sum(item['total'] for item in cart)

    
    return render_template("cart/cart.html", cart = cart, totalPrice = totalPrice)

def placeOrder():
    data =  request.json
    cart = data['cart']
    
    # cart = session.get('cart', [])
    # # session['cart'] = []

    orders = session.get('orders', [])
    if(not orders):
        orders = []
    orders.append(cart)

    session['orders'] = orders
    
    print("placed order for ", cart)

    return redirect("/")

def profile():
    orders = session.get('orders', [])
    print("orders", orders)
    return render_template("profile/profile.html", orders = orders, user_id=session.get('user_id'))

def generateReceipt():
    print("########################Generating receipt#######################")
   
    data = request.json
    order_index = data['index']
    order_data = session.get('orders', [])

    if order_index < 0 or order_index >= len(order_data):
        raise ValueError("Invalid order index")

    selected_order = order_data[order_index]
    pdf_data = generatePdf(selected_order)
    response = make_response(pdf_data)
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = 'attachment; filename=receipt.pdf'

    return response


def generatePdf(order_data):
    pdf_buffer = io.BytesIO()
    pdf_canvas = canvas.Canvas(pdf_buffer)

    pdf_canvas.drawString(100, 800, f"Order Receipt")
    pdf_canvas.drawString(100, 780, f"------------------------")

    total_amount = 0  

    for index, order_item in enumerate(order_data, start=1):
        item_name = order_item.get('name', '')
        quantity = order_item.get('quantity', 0)
        price = order_item.get('price', 0)
        total = order_item.get('total', 0)

        pdf_canvas.drawString(
            100,
            780 - index * 20,
            f"Item {index}: {item_name}, Quantity: {quantity}, Price: {price}, Total: {total}"
        )

        total_amount += total

    
    pdf_canvas.drawString(100, 780, f"------------------------")
    pdf_canvas.drawString(100, 780 - (index + 1) * 20, f"Overall Total: {total_amount}")
    pdf_canvas.save()

    pdf_data = pdf_buffer.getvalue()
    pdf_buffer.close()

    return pdf_data

AA1/routes/blueprint.py
from flask import Blueprint
from controllers.controller import index, login, logout, profile, order, addAddress, addToCart, cart, placeOrder, generateReceipt

blueprint = Blueprint('blueprint', __name__)

blueprint.route('/', methods=['GET'])(index)
blueprint.route('/login', methods=['GET', 'POST'])(login)
blueprint.route('/logout', methods=['GET'])(logout)
blueprint.route("/order", methods=['GET', 'POST'])(order)
blueprint.route("/placeOrder", methods=['GET', 'POST'])(placeOrder)
blueprint.route("/addAddress", methods=["POST"])(addAddress)
blueprint.route("/addToCart", methods=["POST"])(addToCart)
blueprint.route("/profile", methods=['GET',"POST"])(profile)
blueprint.route("/cart", methods=['GET',"POST"])(cart)

blueprint.route("/generateReceipt", methods=["GET","POST"])(generateReceipt)

AA1/templates/cart/cart.html
{% extends "main.jinja" %}
{% block main %}

<script>
    var cart = {{ cart | tojson }};
    var totalPrice = {{ totalPrice }};
</script>

{% include("cart/cart_script.jinja") %}
{% include("cart/cart_style.jinja") %}

<div class="m-5 pt-5">
    <div class="row mt-5">
        <div class="col-sm-12 col-md-12 col-lg-12 p-5 right-section">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <h3 style="color: #828282;"><b>Cart</b></h3>
                </div>
                {% if not cart %}
                    <h6 style="color: #828282;">Cart is empty!</h6>
                {% else %}
                    {% for product in cart %}
                    <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
                        <div class="row">
                            <div class="col-sm-2 col-md-2 col-lg-2">
                                <img src="{{product['image']}}" class="product-img" width="100%" />
                            </div>
                            <div class="col-sm-6 col-md-6 col-lg-6">
                                <div class="row">
                                    <div class="col-sm-12 col-md-12 col-lg-12">
                                        <p>Name: {{product['name']}}</p>
                                    </div><div class="col-sm-12 col-md-12 col-lg-12">
                                        <p>Price: ${{product['price']}}</p>
                                    </div>
                                    <div class="col-sm-12 col-md-12 col-lg-12">
                                        <p>Quantity: {{product['quantity']}}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-2 col-md-2 col-lg-2">
                                Total: ${{product['total']}}
                            </div>
                        </div>
                        <hr />
                    </div>
                    {% endfor %}
                {% endif %}
                <div class="col-sm-12 col-md-12 col-lg-12 mt-2">
                    <div class="row">
                        <div class="col-sm-6 col-md-6 col-lg-6">
                            <p><b>Total Amount</b></p>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-6">
                            <p><b id="total-price"></b>${{totalPrice}}</p>
                        </div>
                    </div>
                    <hr />
                </div>
                <div class="col-sm-12 col-md-12 col-lg-12 mt-2">
                    <button class="order-btn"><b>Place Order</b></button>
                </div>
            </div>
        </div>
        <!-- <div class="col-sm-12 col-md-12 col-lg-7 p-5 mr-5 left-section">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <h3 style="color: #828282;"><b>Addresses</b></h3>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-12 addresses">
                    {% if addresses | length == 0 %}
                    <h6 style="color: #828282;">No addresses found!</h6>
                    {% else %}
                    {% for address in addresses %}
                    <input id="address-{{address['id']}}" type="radio" name="address" value="{{address['id']}}" />
                    <label for="address-{{address['id']}}" title="address">
                        <p>{{address['house_number']}}, {{address["city"]}}, {{address['state']}},
                            {{address['country']}} - {{address['pin_code']}}</p>
                    </label>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <h3 style="color: #828282;"><b>New Shipping Details</b></h3>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-12 mt-5">
                    <textarea type="text" name="house_number" id="house_number" class="order-input"
                        placeholder="House Number" rows=4></textarea>
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 mt-5">
                    <input type="text" name="city" id="city" class="order-input" placeholder="City" />
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 mt-5">
                    <input type="text" name="state" id="state" class="order-input" placeholder="State" />
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 mt-5">
                    <input type="text" name="country" id="country" class="order-input" placeholder="Country" />
                </div>
                <div class="col-sm-6 col-md-6 col-lg-6 mt-5">
                    <input type="text" name="pin_code" id="pin_code" class="order-input" placeholder="PIN Code" />
                </div>
            </div>
            <div class="row mt-5">
                <button class="address-btn"><b>Save Address</b></button>
            </div>
        </div>  -->
    </div>
</div>

{% endblock %}

AA1/templates/cart/cart_script.jinja
<script>
    $(function(){
        
        $(".order-btn").click(function(){
            
            var cartData = JSON.stringify({ cart: cart, totalPrice: totalPrice });

            $.ajax({
                url: "{{url_for('blueprint.placeOrder')}}",
                type: "post",
                contentType: 'application/json',
                data: cartData,
                success: function (result) {
                    Swal.fire(
                        'Order Placed!'
                    ).then(() => {
                        window.location.href = "/"
                    })
                },
                error: function (result) {
                    Swal.fire(
                        'Uh Oh!',
                        result.responseJSON.message,
                        'error'
                    )
                }
            })
        })

    })
</script>

AA1/templates/cart/cart_style.jinja
<style>
    .left-section {
        background-color: white;
        box-shadow: 0 4px 6px -2px rgba(0, 0, 0, 0.5);
    }
    .right-section {
        background-color: white;
        box-shadow: 0 4px 6px -2px rgba(0, 0, 0, 0.5);
    }
    .order-input {
        width: 100%;
        padding: 0.5em;
        color: #828282;
        border: 1px solid #828282;
    }
    .order-input::placeholder {
        color: #828282;
    }
    .product-img {
        border-radius: 1em;
        box-shadow: 0 4px 6px -2px rgba(0, 0, 0, 0.5);
    }
    .order-btn {
        background-color: #442ea6;
        width: 100%;
        padding: 1em;
        color: white;
        border: none;
        font-size: 1.5em;
    }
    .address-btn {
        background-color: #442ea6;
        width: 100%;
        padding: 1em;
        color: white;
        border: none;
        font-size: 1em;
    }
    .addresses input[type=radio] {
        display: none
    }
    .addresses label {
        border: 1px solid black;
        padding: 1em;
        background-color: white;
        width: 100%;
    }
    .addresses input[type=radio]:checked+label {
        border: 3px solid #442ea6;
        background-color: #fafafa;
        width: 100%;
    }
    .d-flex{
  gap:20px;
}
</style>

AA1/templates/dashboard/dashboard_script.jinja
<script>
    
</script>

AA1/templates/dashboard/dashboard_style.jinja
<style>
    .product-img {
        border-radius: 1em;
        box-shadow: 0 4px 6px -2px rgba(0, 0, 0, 0.5);
        max-width: 100%;
    }

    .star-rating {
        direction: rtl;
        display: inline-block;
    }

    .star-rating input[type=radio] {
        display: none
    }

    .star-rating label {
        color: #bbb;
        font-size: 18px;
        padding: 0;
        cursor: pointer;
        -webkit-transition: all .3s ease-in-out;
        transition: all .3s ease-in-out
    }

    .star-rating label:hover,
    .star-rating label:hover ~ label,
    .star-rating input[type=radio]:checked ~ label {
        color: #f2b600
    }

    .price-strike {
        color: #828282;
        text-decoration:line-through;
    }

    .purchase-btn {
        background-color: white;
        padding: 0.5em 3em;
        border: none;
        border-radius: 2em;
        box-shadow: 0 4px 6px -2px rgba(0, 0, 0, 0.5);
    }
</style>

AA1/templates/editor/editor_style.jinja
<style>
    body {
        background-color: #5032b1;
    }
    .CodeMirror {
        border: 1px solid black;
    }
    .execute-btn {
        padding: 1em;
        border: none;
        width: 30%;
        font-size: 1.3em;
        border-radius: 1em;
        box-shadow: 0 4px 6px -2px rgba(0, 0, 0, 0.5);
    }
    #result_box {
        background-color: white;
        min-height: 30vh;
    }
</style>

AA1/templates/help/help.html
{% extends "main.jinja" %}
{% block main %}

{% include("help/help_script.jinja") %}
{% include("help/help_style.jinja") %}

<div class="m-5">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-8 offset-lg-2 text-center pb-4" id="help_box">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white help-title p-4">
                    <h1><b>Help Center</b></h1>
                    <p>We are here to help you</p>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-12 text-center mt-4">
                    <input type="text" name="title" placeholder="Title" id="title" class="help-input" />
                </div>
                <div class="col-sm-12 col-md-12 col-lg-12 text-center mt-2">
                    <textarea name="description" rows=4 placeholder="Describe the issue" id="description"
                        class="help-input"></textarea>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-12 text-center mt-5">
                    <button class="attach-btn text-white">Upload an attachment</button>
                    <input type="file" name="attachment" id="attachment" />
                    <div>
                        <p id="attachment_name"></p>
                    </div>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-12 text-center mt-5">
                    <button class="submit-btn text-white">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

AA1/templates/login/login.html
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;900&display=swap" rel="stylesheet">

    <!-- Sweet Alert -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    
    {% include("login/login_script.jinja") %}
    {% include("login/login_style.jinja") %}
    <div class="main-container">
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-6 text-center" id="left-section">
                <div class="row mt-5">
                    <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white">
                        <h1 class="login-logo"><b>Toy-e-Wagon</b></h1>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-12 text-center p-3">
                        <img src="{{'static/images/login.png'}}" width="90%" />
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6 align-self-center pl-5 pr-5" id="right-section">
                <form action="{{url_for('blueprint.login')}}" method="POST">
                <div class="row pl-5 pr-5">
                    <div class="col-sm-12 col-md-12 col-lg-12 pl-5 pr-5">
                        <h1>Login</h1>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-12 pl-5 pr-5 mt-2">
                        <p class="paragraph-text">Login into your account to view our products and access your profile
                            to track orders</p>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-12 pl-5 pr-5 mt-5">
                        <input type="text" name="email" class="login-input" id="email" placeholder="E-mail address" />
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-12 pl-5 pr-5 mt-5">
                        <div class="inputWithIcon">
                            <input type="password" name="password" class="login-input" id="password"
                                placeholder="Password" />
                            <i class="fa fa-eye-slash fa-lg fa-fw" id="password_icon" onclick="show_hide_password();"
                                aria-hidden="true"></i>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-12 pl-5 pr-5 mt-5 text-right">
                        <button type="submit" class="login-button">Login</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    <div id="loader">
        <!-- <img src="/static/images/loading.gif" class="loading-gif"> -->
    </div>
</body>

</html>

AA1/templates/login/login_script.jinja
<script>
   
    function show_hide_password() {
        if ($("#password_icon").hasClass("fa-eye")) {
            $("#password_icon").removeClass("fa-eye").addClass("fa-eye-slash")
            $("#password").attr("type", "password");
        } else {
            $("#password_icon").removeClass("fa-eye-slash").addClass("fa-eye")
            $("#password").attr("type", "text");
        }
    }
</script>

AA1/templates/main.jinja
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;900&display=swap" rel="stylesheet">

    <!-- Sweet Alert -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include("main_script.jinja") %}
    {% include("main_style.jinja") %}
</head>

<body>
    <div class="main-container">
        <nav class="navbar fixed-top navbar-expand navbar-light" style="background: #442ea6;">
            <div class="navbar-collapse" id="navbarsExample02">
                <a class="navbar-brand pl-5 pr-5" href="/">
                    <span style="font-size: 2em; color: white;"><b>Toy-e-Wagon</b></span>
                </a>
                <div>
                    <div class="searchInputWrapper">
                        <input class="searchInput" type="text" placeholder='Search'>
                        <i class="searchInputIcon fa fa-search"></i>
                        </input>
                    </div>
                </div>
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item align-self-center" id="dashboard_navigator">
                        <a class="nav-link" href="{{url_for('blueprint.index')}}">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2">
                                    <i class="fa fa-tachometer nav-icon"></i>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white">
                                    <p class="nav-text">Dashboard</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item align-self-center" id="profile_navigator">
                        <a class="nav-link" href="{{url_for('blueprint.profile')}}?id={{user_id}}">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2">
                                    <i class="fa fa-user nav-icon"></i>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white">
                                    <p class="nav-text">Profile</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item align-self-center" id="cart">
                        <a class="nav-link" href="{{url_for('blueprint.cart')}}?id={{user_id}}">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2">
                                    <i class="fa fa-shopping-cart nav-icon"></i>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white">
                                    <p class="nav-text">Cart</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item align-self-center">
                        <a class="nav-link" href="/logout">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2">
                                    <i class="fa fa-sign-out nav-icon"></i>
                                </div>
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white">
                                    <p class="nav-text">Logout</p>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <div class="row">
                                <div class="col-sm-12 col-md-12 col-lg-12 text-center text-white mt-2 help-button">
                                    <i class="fa fa-question-circle-o nav-icon"></i>
                                    <span class="nav-text p-3" style="font-size: 1.5em;">Help</span>
                                </div>
                            </div>
                        </a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-md-0"> </form>
            </div>
        </nav>
    </div>
    <div>
        {% block main %}{% endblock %}
    </div>
</body>

</html>

AA1/templates/main_script.jinja
<script>
    function logout_user() {
        $.ajax({
            url: "{{url_for('blueprint.logout')}}",
            type: 'post',
            success: function (result) {
                window.location.href = "{{url_for('blueprint.login')}}";
            },
            error: function (result) {
                alert(result.responseJSON.message);
            }
        });
    }
</script>

AA1/templates/order/order_script.jinja
<script>
    $(function(){
        
        $(".order-btn").click(function(){
            let searchParams = new URLSearchParams(window.location.search)
            let data = {
                product_id: searchParams.get('id'),
                price: parseFloat($("#selling-price").html().substring(1)),
                quantity: parseInt($("#quantity").html()),
                total: parseFloat($("#total-price").html().substring(1)), 
                name: $("#product-name").html(),
                image: $("#product-img").attr('src')
            }
            $.ajax({
                url: "{{url_for('blueprint.addToCart')}}",
                type: "post",
                data: JSON.stringify(data),
                dataType: 'json',
                contentType: 'application/json',
                success: function (result) {
                    Swal.fire(
                        'Added to the cart!'
                    ).then(() => {
                        window.location.href = "/cart"
                    })
                },
                error: function (result) {
                    Swal.fire(
                        'Uh Oh!',
                        result.responseJSON.message,
                        'error'
                    )
                }
            })
        })

        $("#btn-dec").click(function(){
            // Get the current value of the input field and parse it as an integer
            var currentQuantity = parseFloat($("#quantity").html());
            var sellingPrice = parseFloat($("#selling-price").html().substring(1));
            var deliveryCharges = parseFloat($("#delivery-charges").html().substring(1));

            if(currentQuantity > 1){
                // Decrement the quantity by 1
                var newQuantity = currentQuantity - 1;
                var total = (newQuantity * sellingPrice) + deliveryCharges
                // Set the new inner HTML of the element
                $("#quantity").html(newQuantity);
                $("#total-price").html('$'+total)
            }

        })

        $("#btn-inc").click(function(){
            // Get the current value of the input field and parse it as an integer
            var currentQuantity = parseFloat($("#quantity").html(), 10);
            var sellingPrice = parseFloat($("#selling-price").html().substring(1));
            var deliveryCharges = parseFloat($("#delivery-charges").html().substring(1));

            // Increment the quantity by 1
            var newQuantity = currentQuantity + 1;

            // Set the new inner HTML of the element
            $("#quantity").html(newQuantity);
            total = (newQuantity * sellingPrice) + deliveryCharges
            $("#total-price").html('$'+total)
        })
    })
</script>